# Generated by Django 5.2.2 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='video',
            field=models.FileField(default=10, upload_to='images/'),
            preserve_default=False,
        ),
    ]
