# Generated by Django 5.2.2 on 2025-07-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_infobox_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobox',
            name='video',
        ),
    ]
