# Generated by Django 5.2.2 on 2025-07-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_remove_infobox_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#1f4e79', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
